#if !defined(AMERICAN_CONQUEST_Azt_NATION)
#define AMERICAN_CONQUEST_Azt_NATION

// Aztoware nations header file

#include "Import.h"

class AztUnits {
public:	
	GAMEOBJ Kri;	// PEASANT
	GAMEOBJ Met;
	GAMEOBJ Lut;
	GAMEOBJ Sha;
	GAMEOBJ Vog;
	GAMEOBJ Ka1; // Kanoe 1
	GAMEOBJ Ka3; // Kanoe 2
	GAMEOBJ Par; // Parom
};

class AztBuildings {
public:
	GAMEOBJ Rud;
	GAMEOBJ Iro;
	GAMEOBJ Coa;
	GAMEOBJ Stn;
	GAMEOBJ Do1;
	GAMEOBJ Do2;
	GAMEOBJ Mel;
	GAMEOBJ Skl;
	GAMEOBJ Hra;
	GAMEOBJ Cen;
	GAMEOBJ Kre;
	GAMEOBJ Blg;
	GAMEOBJ Ver;
	GAMEOBJ Blg2;
};

class AztUpgrades {
public:
	GAMEOBJ CEN15; //LIFE GRP 1 AtcSha_ +400%
	GAMEOBJ CEN14; //DAMAGE WEAPONKIND MEDIK AtcSha_ +15
	GAMEOBJ CEN13; //BUILD GRP 1 AtcSha_ -50%
	GAMEOBJ EnBLG; //ENABLE UNITS GRP 1 AtcBlg_
	GAMEOBJ CEN11; //BUILD GRP 4 AtcDo2_ AtcDo1_ AtcBlg_ MayBlg2_ -75%

	GAMEOBJ CEN07; //BUILD GRP 1 AtcMet_ -50%
	GAMEOBJ CEN01; //EFFECT_FOOD +4
	GAMEOBJ CEN02; //EFFECT_FOOD +4
	GAMEOBJ CEN03; //EFFECT_FOOD +5
	GAMEOBJ CEN05; //DAMAGE WEAPONKIND PIKA GRP 2 AtcMet_ AtcVog_ +5 
	GAMEOBJ CEN10; //EFFECT_FOOD +2000
	
	GAMEOBJ Met_LIFE; //LIFE GRP 2 AtcMet_ AtcLut_ +10%
	GAMEOBJ Do2_ENABLE; //ENABLE UNITS GRP 1 AtcDo2_
	GAMEOBJ Kre_RAZBROS; //RAZBROS GRP 1 AtcLut_ -35%
	GAMEOBJ Kre_RAZBROS1; //RAZBROS GRP 1 AtcLut_ -35%
	GAMEOBJ Mel_GETRES; //EFFECT_FOOD +14
	GAMEOBJ Mel_GETRES2; //EFFECT_FOOD +25
	GAMEOBJ UPSTATCKRE0; //UPSTAGE0
	GAMEOBJ UPSTATCKRE1; //UPSTAGE1
	GAMEOBJ UPSTATCKRE2; //UPSTAGE2	

	// Center
	GAMEOBJ ConstrBuild1; //CEN11AC

	GAMEOBJ BlgPrice; //CEN25AC COST AtcBlg(AC) GRP 2 WOOD -50% STONE -50%
	
	GAMEOBJ CEN52; //EFFECT_FOOD +3000
	GAMEOBJ CEN12; //EFFECT_FOOD +3000
	GAMEOBJ UPSTATCVER0; //UPSTAGE0
	GAMEOBJ UPSTATCVER1; //UPSTAGE1

	GAMEOBJ MetBuild; //CEN07AC BUILD GRP 1 AtcMet(AC) -50%
	GAMEOBJ MetProtArrow; //CEN06AC PROTECTION GRP 1 STRELA AtcMet(AC) +25
	GAMEOBJ LutProtPika; //AtcVoiS PROTECTION GRP 1 PIKA AtcLut(AC) +5
	GAMEOBJ WarLife; //AtcMet(AC)LIFE LIFE GRP 2 AtcMet(AC) AtcLut(AC) +10%
	//CEN05AC DAMAGE WEAPONKIND MECH GRP 1  AtcVog(AC) +5 

	// Mine
	GAMEOBJ Gld0;
	GAMEOBJ Gld1;
	GAMEOBJ Gld2;
	GAMEOBJ Gld3;
	GAMEOBJ Gld4;
	GAMEOBJ Gld5;

	GAMEOBJ Stn0;
	GAMEOBJ Stn1;
	GAMEOBJ Stn2;
	GAMEOBJ Stn3;
	GAMEOBJ Stn4;
	GAMEOBJ Stn5;

	GAMEOBJ Iro0;
	GAMEOBJ Iro1;
	GAMEOBJ Iro2;

	// Kri
	GAMEOBJ KriBu1;	// -15% build speed
	GAMEOBJ KriBu2;	// -25% build speed

	// Met
	GAMEOBJ MetPika1; // CEN05AC +5

	GAMEOBJ Met_ATTACK; //DAMAGE WEAPONKIND PIKA AtcMet_ +1
	GAMEOBJ Met_ATTACK3; //DAMAGE WEAPONKIND PIKA AtcMet_ +2
	GAMEOBJ Met_ATTACK4; //DAMAGE WEAPONKIND PIKA AtcMet_ +3
	GAMEOBJ Met_ATTACK5; //DAMAGE WEAPONKIND PIKA AtcMet_ +2
	GAMEOBJ Met_ATTACK6; //DAMAGE WEAPONKIND PIKA AtcMet_ +1
	GAMEOBJ Met_ATTACK7; //DAMAGE WEAPONKIND PIKA AtcMet_ +1
	GAMEOBJ Met_SHIELD; //PROTECTION GRP 2 MECH PIKA AtcMet_ +1
	GAMEOBJ Met_SHIELD3; //PROTECTION GRP 2 MECH PIKA AtcMet_ +1
	GAMEOBJ Met_SHIELD4; //PROTECTION GRP 2 MECH PIKA AtcMet_ +3
	GAMEOBJ Met_SHIELD5; //PROTECTION GRP 2 MECH PIKA AtcMet_ +2
	GAMEOBJ Met_SHIELD6; //PROTECTION GRP 2 MECH PIKA  AtcMet_ +2
	GAMEOBJ Met_SHIELD7; //PROTECTION GRP 2 MECH PIKA AtcMet_ +2

	// Lut
	GAMEOBJ Lut_ATTACK; //DAMAGE WEAPONKIND MECH AtcLut_ +1
	GAMEOBJ Lut_ATTACK3; //DAMAGE WEAPONKIND MECH AtcLut_ +1
	GAMEOBJ Lut_ATTACK4; //DAMAGE WEAPONKIND MECH AtcLut_ +1                                   
	GAMEOBJ Lut_ATTACK5; //DAMAGE WEAPONKIND MECH AtcLut_ +1
	GAMEOBJ Lut_ATTACK6; //DAMAGE WEAPONKIND MECH AtcLut_ +1
	GAMEOBJ Lut_ATTACK7; //DAMAGE WEAPONKIND MECH AtcLut_ +1
	GAMEOBJ Lut_SHIELD; //PROTECTION GRP 2 MECH PIKA AtcLut_ +2
	GAMEOBJ Lut_SHIELD3; //PROTECTION GRP 2 MECH PIKA AtcLut_ +1
	GAMEOBJ Lut_SHIELD4; //PROTECTION GRP 2 MECH PIKA AtcLut_ +3
	GAMEOBJ Lut_SHIELD5; //PROTECTION GRP 2 MECH PIKA AtcLut_ +1
	GAMEOBJ Lut_SHIELD6; //PROTECTION GRP 2 MECH PIKA  AtcLut_ +2
	GAMEOBJ Lut_SHIELD7; //PROTECTION GRP 2 MECH PIKA AtcLut_ +1

	// Vog	
	GAMEOBJ Vog_ATTACK; //DAMAGE WEAPONKIND PIKA AtcVog_ +1
	GAMEOBJ Vog_ATTACK3; //DAMAGE WEAPONKIND PIKA AtcVog_ +2
	GAMEOBJ Vog_ATTACK4; //DAMAGE WEAPONKIND PIKA AtcVog_ +3
	GAMEOBJ Vog_ATTACK5; //DAMAGE WEAPONKIND PIKA AtcVog_ +4
	GAMEOBJ Vog_ATTACK6; //DAMAGE WEAPONKIND PIKA AtcVog_ +5
	GAMEOBJ Vog_ATTACK7; //DAMAGE WEAPONKIND PIKA AtcVog_ +50
	GAMEOBJ Vog_SHIELD; //PROTECTION GRP 2 MECH PIKA AtcVog_ +5
	GAMEOBJ Vog_SHIELD3; //PROTECTION GRP 2 MECH PIKA AtcVog_ +6
	GAMEOBJ Vog_SHIELD4; //PROTECTION GRP 2 MECH PIKA AtcVog_ +7
	GAMEOBJ Vog_SHIELD5; //PROTECTION GRP 2 MECH PIKA AtcVog_ +8
	GAMEOBJ Vog_SHIELD6; //PROTECTION GRP 2 MECH PIKA  AtcVog_ +9
	GAMEOBJ Vog_SHIELD7; //PROTECTION GRP 2 MECH PIKA AtcVog_  +10

	// Sha
	GAMEOBJ ShaBuild1; //CEN13AC
	GAMEOBJ ShaLife1; //CEN15AC
	GAMEOBJ ShaMedik1; //CEN14AC

	// Parom
	GAMEOBJ ParSpeed1; //CEN102DE
	GAMEOBJ ParSpeed2; //CEN103DE
	GAMEOBJ ParSpeed3; //CEN104DE
	GAMEOBJ ParSpeed4; //CEN105DE
	GAMEOBJ ParSpeed5; //CEN106DE
	GAMEOBJ ParSpeed6; //CEN107DE

	// Kanoe 3 build speed
	GAMEOBJ Ka3Build1; //CEN96DE
	GAMEOBJ Ka3Build2; //CEN97DE
	GAMEOBJ Ka3Build3; //CEN98DE
	GAMEOBJ Ka3Build4; //CEN99DE
	GAMEOBJ Ka3Build5; //CEN100DE
	GAMEOBJ Ka3Build6; //CEN101DE

	// Fishing
	GAMEOBJ Ka1Fishing1; //CEN90DE
	GAMEOBJ Ka1Fishing2; //CEN91DE
	GAMEOBJ Ka1Fishing3; //CEN92DE
	GAMEOBJ Ka1Fishing4; //CEN93DE
	GAMEOBJ Ka1Fishing5; //CEN94DE
	GAMEOBJ Ka1Fishing6; //CEN95DE

};

// FIELD(MA)       FIELD
class AztNation {
public:
	AztNation();
	AztUnits Unit;
	AztBuildings Build;
	AztUpgrades Upg;
};
extern AztNation Azt;

#endif
